/*
  GENERATED by scripts/memo-icons.mjs. Re-run it after using a new icon instead of editing.

  Each lucide icon wrapped in React.memo: an icon is a react-native-svg drawing that used to
  re-render with its parent even when its size and colour had not changed.
*/
import React from 'react'
import {
  Activity as LucideActivity,
  AlertCircle as LucideAlertCircle,
  AlertTriangle as LucideAlertTriangle,
  ArrowDown as LucideArrowDown,
  ArrowLeft as LucideArrowLeft,
  ArrowRight as LucideArrowRight,
  ArrowUp as LucideArrowUp,
  Award as LucideAward,
  Bell as LucideBell,
  BellOff as LucideBellOff,
  BookOpen as LucideBookOpen,
  Bookmark as LucideBookmark,
  BookmarkPlus as LucideBookmarkPlus,
  Bot as LucideBot,
  Brain as LucideBrain,
  CalendarCheck as LucideCalendarCheck,
  CalendarClock as LucideCalendarClock,
  CalendarDays as LucideCalendarDays,
  Camera as LucideCamera,
  Check as LucideCheck,
  CheckCircle2 as LucideCheckCircle2,
  ChevronDown as LucideChevronDown,
  ChevronLeft as LucideChevronLeft,
  ChevronRight as LucideChevronRight,
  ChevronUp as LucideChevronUp,
  Circle as LucideCircle,
  Clock as LucideClock,
  Cloud as LucideCloud,
  CloudOff as LucideCloudOff,
  Cookie as LucideCookie,
  Download as LucideDownload,
  Droplets as LucideDroplets,
  Dumbbell as LucideDumbbell,
  Eraser as LucideEraser,
  Flame as LucideFlame,
  Footprints as LucideFootprints,
  Gauge as LucideGauge,
  History as LucideHistory,
  Home as LucideHome,
  ImageIcon as LucideImageIcon,
  Info as LucideInfo,
  Lightbulb as LucideLightbulb,
  Link2 as LucideLink2,
  MailCheck as LucideMailCheck,
  Minus as LucideMinus,
  Moon as LucideMoon,
  MoreHorizontal as LucideMoreHorizontal,
  PersonStanding as LucidePersonStanding,
  Play as LucidePlay,
  Plus as LucidePlus,
  RefreshCw as LucideRefreshCw,
  Repeat as LucideRepeat,
  RotateCcw as LucideRotateCcw,
  Ruler as LucideRuler,
  Salad as LucideSalad,
  Scale as LucideScale,
  Search as LucideSearch,
  Send as LucideSend,
  ServerCrash as LucideServerCrash,
  ShieldCheck as LucideShieldCheck,
  SkipForward as LucideSkipForward,
  SlidersHorizontal as LucideSlidersHorizontal,
  Smartphone as LucideSmartphone,
  Sparkles as LucideSparkles,
  Sun as LucideSun,
  Sunrise as LucideSunrise,
  Target as LucideTarget,
  Timer as LucideTimer,
  Trash2 as LucideTrash2,
  TrendingDown as LucideTrendingDown,
  TrendingUp as LucideTrendingUp,
  TriangleAlert as LucideTriangleAlert,
  Trophy as LucideTrophy,
  User as LucideUser,
  Utensils as LucideUtensils,
  WifiOff as LucideWifiOff,
  X as LucideX,
} from 'lucide-react-native'

/** Same type as the original, so every call site and prop type keeps working. */
const memo = <T extends React.ComponentType<any>>(Icon: T): T => React.memo(Icon) as unknown as T

export const Activity = memo(LucideActivity)
export const AlertCircle = memo(LucideAlertCircle)
export const AlertTriangle = memo(LucideAlertTriangle)
export const ArrowDown = memo(LucideArrowDown)
export const ArrowLeft = memo(LucideArrowLeft)
export const ArrowRight = memo(LucideArrowRight)
export const ArrowUp = memo(LucideArrowUp)
export const Award = memo(LucideAward)
export const Bell = memo(LucideBell)
export const BellOff = memo(LucideBellOff)
export const BookOpen = memo(LucideBookOpen)
export const Bookmark = memo(LucideBookmark)
export const BookmarkPlus = memo(LucideBookmarkPlus)
export const Bot = memo(LucideBot)
export const Brain = memo(LucideBrain)
export const CalendarCheck = memo(LucideCalendarCheck)
export const CalendarClock = memo(LucideCalendarClock)
export const CalendarDays = memo(LucideCalendarDays)
export const Camera = memo(LucideCamera)
export const Check = memo(LucideCheck)
export const CheckCircle2 = memo(LucideCheckCircle2)
export const ChevronDown = memo(LucideChevronDown)
export const ChevronLeft = memo(LucideChevronLeft)
export const ChevronRight = memo(LucideChevronRight)
export const ChevronUp = memo(LucideChevronUp)
export const Circle = memo(LucideCircle)
export const Clock = memo(LucideClock)
export const Cloud = memo(LucideCloud)
export const CloudOff = memo(LucideCloudOff)
export const Cookie = memo(LucideCookie)
export const Download = memo(LucideDownload)
export const Droplets = memo(LucideDroplets)
export const Dumbbell = memo(LucideDumbbell)
export const Eraser = memo(LucideEraser)
export const Flame = memo(LucideFlame)
export const Footprints = memo(LucideFootprints)
export const Gauge = memo(LucideGauge)
export const History = memo(LucideHistory)
export const Home = memo(LucideHome)
export const ImageIcon = memo(LucideImageIcon)
export const Info = memo(LucideInfo)
export const Lightbulb = memo(LucideLightbulb)
export const Link2 = memo(LucideLink2)
export const MailCheck = memo(LucideMailCheck)
export const Minus = memo(LucideMinus)
export const Moon = memo(LucideMoon)
export const MoreHorizontal = memo(LucideMoreHorizontal)
export const PersonStanding = memo(LucidePersonStanding)
export const Play = memo(LucidePlay)
export const Plus = memo(LucidePlus)
export const RefreshCw = memo(LucideRefreshCw)
export const Repeat = memo(LucideRepeat)
export const RotateCcw = memo(LucideRotateCcw)
export const Ruler = memo(LucideRuler)
export const Salad = memo(LucideSalad)
export const Scale = memo(LucideScale)
export const Search = memo(LucideSearch)
export const Send = memo(LucideSend)
export const ServerCrash = memo(LucideServerCrash)
export const ShieldCheck = memo(LucideShieldCheck)
export const SkipForward = memo(LucideSkipForward)
export const SlidersHorizontal = memo(LucideSlidersHorizontal)
export const Smartphone = memo(LucideSmartphone)
export const Sparkles = memo(LucideSparkles)
export const Sun = memo(LucideSun)
export const Sunrise = memo(LucideSunrise)
export const Target = memo(LucideTarget)
export const Timer = memo(LucideTimer)
export const Trash2 = memo(LucideTrash2)
export const TrendingDown = memo(LucideTrendingDown)
export const TrendingUp = memo(LucideTrendingUp)
export const TriangleAlert = memo(LucideTriangleAlert)
export const Trophy = memo(LucideTrophy)
export const User = memo(LucideUser)
export const Utensils = memo(LucideUtensils)
export const WifiOff = memo(LucideWifiOff)
export const X = memo(LucideX)
