#!/usr/bin/env node
/**
 * Wires the release keystore into the generated Android project.
 *
 * `android/` is regenerated by `expo prebuild` (Continuous Native Generation), so any
 * edit made there is disposable — this script re-applies the signing config after every
 * regeneration instead of asking anyone to remember a manual patch.
 *
 * Reads credentials/keystore.properties (git-ignored) and:
 *   1. copies the keystore next to the app module, where Gradle expects it
 *   2. appends the credentials to android/gradle.properties
 *   3. rewrites the release signingConfig, which Expo's template otherwise points at the
 *      DEBUG keystore — shippable-looking but unupgradeable, since Android refuses an
 *      update signed with a different key
 *
 * No-ops with a clear message when the credentials are absent, so a fresh clone can still
 * build a debug variant.
 */
import { copyFile, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const propsPath = path.join(root, 'credentials', 'keystore.properties')
const androidDir = path.join(root, 'android')

if (!existsSync(propsPath)) {
  console.log('[apply-signing] no credentials/keystore.properties — skipping (debug builds still work)')
  process.exit(0)
}
if (!existsSync(androidDir)) {
  console.error('[apply-signing] android/ missing. Run: npx expo prebuild --platform android')
  process.exit(1)
}

const props = Object.fromEntries(
  (await readFile(propsPath, 'utf8'))
    .split('\n')
    .filter(line => line.trim() && !line.trim().startsWith('#'))
    .map(line => {
      const i = line.indexOf('=')
      return [line.slice(0, i).trim(), line.slice(i + 1).trim()]
    }),
)

const storeFile = props.MACROFIT_UPLOAD_STORE_FILE
await copyFile(path.join(root, 'credentials', storeFile), path.join(androidDir, 'app', storeFile))

// 2. credentials into gradle.properties (idempotent)
const gpPath = path.join(androidDir, 'gradle.properties')
let gp = await readFile(gpPath, 'utf8')
gp = gp.replace(/\n# --- MacroFit signing ---[\s\S]*?# --- end MacroFit signing ---\n/, '\n')
gp += [
  '',
  '# --- MacroFit signing ---',
  ...Object.entries(props).map(([k, v]) => `${k}=${v}`),
  '# --- end MacroFit signing ---',
  '',
].join('\n')
await writeFile(gpPath, gp)

// 3. real release signingConfig
const bgPath = path.join(androidDir, 'app', 'build.gradle')
let bg = await readFile(bgPath, 'utf8')

if (!bg.includes('macrofitRelease')) {
  bg = bg.replace(
    /signingConfigs \{\n(\s+)debug \{/,
    `signingConfigs {\n$1macrofitRelease {\n$1    storeFile file(MACROFIT_UPLOAD_STORE_FILE)\n$1    storePassword MACROFIT_UPLOAD_STORE_PASSWORD\n$1    keyAlias MACROFIT_UPLOAD_KEY_ALIAS\n$1    keyPassword MACROFIT_UPLOAD_KEY_PASSWORD\n$1}\n$1debug {`,
  )
}

const before = bg
bg = bg.replace(
  /(release \{\n(?:.*\n)*?\s*)signingConfig signingConfigs\.debug/,
  '$1signingConfig signingConfigs.macrofitRelease',
)
if (bg === before && !bg.includes('signingConfig signingConfigs.macrofitRelease')) {
  console.error('[apply-signing] could not rewrite the release signingConfig — check android/app/build.gradle')
  process.exit(1)
}

await writeFile(bgPath, bg)
console.log('[apply-signing] release builds will use the MacroFit keystore')
