#!/usr/bin/env node
/**
 * Every lucide icon the app uses, wrapped in React.memo, in src/components/icons.ts; and every
 * import of lucide-react-native rewritten to come from there.
 *
 *   node scripts/memo-icons.mjs
 *
 * WHY: an icon is a react-native-svg drawing, among the most expensive things to re-render in
 * JS, and it re-rendered whenever its parent did, with the same size and colour. Its props are
 * all primitives, so a memo holds and the drawing is skipped.
 *
 * Re-run it after adding an icon: it collects names from both lucide-react-native imports and
 * '@/components/icons' imports, so it is safe to run any number of times. Named imports only;
 * `import * as` from lucide would bundle all ~1,500 icons.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const OUT = path.join(root, 'src/components/icons.ts')
const IMPORT = /import\s+\{([^}]*)\}\s+from\s+'(lucide-react-native|@\/components\/icons)'/g

const files = []
const walk = dir => {
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name)
    if (statSync(full).isDirectory()) walk(full)
    else if (/\.(ts|tsx)$/.test(name) && full !== OUT) files.push(full)
  }
}
walk(path.join(root, 'app'))
walk(path.join(root, 'src'))

const names = new Set()
let rewritten = 0
for (const file of files) {
  const source = readFileSync(file, 'utf8')
  let changed = false
  const next = source.replace(IMPORT, (_whole, list, from) => {
    for (const part of list.split(',')) {
      const name = part.trim().split(/\s+as\s+/)[0].trim()
      if (name) names.add(name)
    }
    if (from === 'lucide-react-native') changed = true
    return `import {${list}} from '@/components/icons'`
  })
  if (changed) {
    writeFileSync(file, next)
    rewritten += 1
  }
}

const sorted = [...names].sort()
writeFileSync(
  OUT,
  [
    '/*',
    '  GENERATED by scripts/memo-icons.mjs. Re-run it after using a new icon instead of editing.',
    '',
    '  Each lucide icon wrapped in React.memo: an icon is a react-native-svg drawing that used to',
    '  re-render with its parent even when its size and colour had not changed.',
    '*/',
    "import React from 'react'",
    'import {',
    ...sorted.map(name => `  ${name} as Lucide${name},`),
    "} from 'lucide-react-native'",
    '',
    '/** Same type as the original, so every call site and prop type keeps working. */',
    'const memo = <T extends React.ComponentType<any>>(Icon: T): T => React.memo(Icon) as unknown as T',
    '',
    ...sorted.map(name => `export const ${name} = memo(Lucide${name})`),
    '',
  ].join('\n'),
)
console.log(`${sorted.length} icons in src/components/icons.ts; ${rewritten} files rewritten`)
